version: "3"
services:
  db:
    image: postgres:11-alpine
    enviroment:
      POSTGRES_PASSWORD: workout
      POSTGRES_USER: workout
      POSTGRES_DB: workout
    ports:
      - "5432:5432"      

# No terminal: docker-compose up -d
# Para verificar se está funcionando : docker ps
